name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Run this workflow only on pushes to the main branch

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3